//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package m.z.imagelocus.activity.map;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.TextView;
import m.z.imagelocus.R.id;
import m.z.imagelocus.R.layout;
import m.z.imagelocus.view.map.LocationMapView;

public final class MapImpressActivity_
    extends MapImpressActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_map_impress);
    }

    private void init_(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
    }

    private void afterSetContentView_() {
        tv_middle = ((TextView) findViewById(id.tv_middle));
        mMapView = ((LocationMapView) findViewById(id.bmapView));
        btn_test = ((Button) findViewById(id.btn_test));
        btn_locate = ((Button) findViewById(id.btn_locate));
        btn_history_next = ((Button) findViewById(id.btn_history_next));
        btn_history_before = ((Button) findViewById(id.btn_history_before));
        btn_right = ((Button) findViewById(id.btn_right));
        {
            View view = findViewById(id.btn_history_next);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MapImpressActivity_.this.btn_history_next_onClick();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_right);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MapImpressActivity_.this.btn_right_onClick();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_locate);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MapImpressActivity_.this.btn_locate_onClick();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_test);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MapImpressActivity_.this.btn_test_onClick();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_history_before);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MapImpressActivity_.this.btn_history_before_onClick();
                    }

                }
                );
            }
        }
        init();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MapImpressActivity_.IntentBuilder_ intent(Context context) {
        return new MapImpressActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MapImpressActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MapImpressActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
